export const GET_HOME_SERVICES_PLANS_REQUEST = "GET_HOME_SERVICES_PLANS_REQUEST";
export const GET_HOME_SERVICES_PLANS_SUCCESS = "GET_HOME_SERVICES_PLANS_SUCCESS";
export const GET_HOME_SERVICES_PLANS_ERROR= "GET_HOME_SERVICES_PLANS_ERROR";

export const TOGGLE_SELECTED_HOME_SERVICES_PLANS= "TOGGLE_SELECTED_HOME_SERVICES_PLANS";
export const RESET_SELECTED_HOME_SERVICES_PLANS = "RESET_SELECTED_HOME_SERVICES_PLANS";
export const GET_SELECTED_HOME_SERVICES_PLANS = "GET_SELECTED_HOME_SERVICES_PLANS";


