//Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS= "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR= "USER_REGISTER_ERROR";

export const GET_USER_LOGGED_REQUEST = "GET_USER_LOGGED_REQUEST";
export const GET_USER_LOGGED_SUCCESS= "GET_USER_LOGGED_SUCCESS";
export const GET_USER_LOGGED_ERROR= "GET_USER_LOGGED_ERROR";
